apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
  namespace: eks-project
spec:
  backoffLimit: 8
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: mongo:7
          command:
            - /bin/bash
            - -c
            - |
              set -e

              echo "⏳ Waiting for MongoDB pods..."

              HOSTS=(
                "mongoset-0.mongo.eks-project.svc.cluster.local:27017"
                "mongoset-1.mongo.eks-project.svc.cluster.local:27017"
              )

              for host in "${HOSTS[@]}"; do
                echo "Checking $host..."
                until mongosh --host $host --quiet --eval "db.adminCommand({ ping: 1 })" >/dev/null 2>&1; do
                  echo "Waiting for $host..."
                  sleep 3
                done
                echo "$host is ready"
              done

              echo "✅ MongoDB pods ready"

              mongosh --host mongoset-0.mongo.eks-project.svc.cluster.local:27017 --eval '
                const config = {
                  _id: "rs0",
                  members: [
                    { _id: 0, host: "mongoset-0.mongo.eks-project.svc.cluster.local:27017" },
                    { _id: 1, host: "mongoset-1.mongo.eks-project.svc.cluster.local:27017" }
                  ]
                };

                try {
                  rs.status();
                  print("Replica set already initialized");
                } catch (e) {
                  print("Initializing replica set...");
                  rs.initiate(config);
                  print("Replica set initialized");
                }
              '

              echo "✅ Done"