apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: eks-project
data:
  DATABASE_HOSTS: |
    - mongoset-0.mongo.eks-project.svc.cluster.local
    - mongoset-1.mongo.eks-project.svc.cluster.local
  DATABASE_PORT: "27017"
  DATABASE_REPLICA_SET: rs0
  LOG_LEVEL: info