apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: eks-project
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongoset-0.mongo.eks-project:27017,mongoset-1.mongo.eks-project:27017/app?replicaSet=rs0"
~
