# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  replicas: 1
  tag: v2   

  
# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  replicas: 1
  tag: v2
  
# ──────────────────────────────────────
# MongoDB
# ──────────────────────────────────────
mongo:
  replicas: 2
  
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress-alb:
  host: myapp.local

ingress1-nginx:
  host: myapp.local  
  