name: Todo app CI + GitOps (ArgoCD)

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

# ---------------- CI ----------------
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


# ---------------- VERSION ----------------
  version:
    name: Generate version
    runs-on: ubuntu-latest
    needs: ci

    outputs:
      version: ${{ steps.ver.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Read current version
      id: ver
      run: |
        if [ ! -f version.txt ]; then
          echo "v1.0.0" > version.txt
        fi

        CURRENT=$(cat version.txt)

        VERSION=${CURRENT#v}

        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

        PATCH=$((PATCH + 1))

        if [ "$PATCH" -gt 9 ]; then
          PATCH=0
          MINOR=$((MINOR + 1))
        fi

        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"

        echo "$NEW_VERSION" > version.txt

        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "Generated: $NEW_VERSION"

# ---------------- DOCKER ----------------
  docker:
    name: Build & Push Images
    runs-on: ubuntu-latest
    needs: version

    env:
      VERSION: ${{ needs.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/frontend-dev:${{ env.VERSION }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/backend-dev:${{ env.VERSION }}


# ---------------- HELM VALIDATION ----------------
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest
    needs: [docker, version]

    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4

      - name: Helm lint
        run: helm lint helm/todo-app

      - name: Helm template test
        run: |
          helm template helm/todo-app \
            --set frontend.tag=${{ needs.version.outputs.version }} \
            --set backend.tag=${{ needs.version.outputs.version }}


# ---------------- GITOPS ----------------
  gitops:
    name: Update ArgoCD Repo
    runs-on: ubuntu-latest
    needs: [validate, version]

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: chimuanyavic7/eks-dev-form
          token: ${{ secrets.GITOPS_TOKEN }}
          ref: main

      - name: Setup yq
        uses: mikefarah/yq@v4.44.3

      - name: Update Helm values
        run: |
          VERSION="${{ needs.version.outputs.version }}"

          echo "Deploying version: $VERSION"

          yq -i ".frontend.tag = strenv(VERSION)" helm/todo-app/values.yaml
          yq -i ".backend.tag = strenv(VERSION)" helm/todo-app/values.yaml

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add helm/todo-app/values.yaml
          git commit -m "deploy: ${{ needs.version.outputs.version }}" || echo "no changes"
          git push