name: Todo app with GitOps (ArgoCD)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

# ---------------- CI / PREP ----------------
  ci:
    name: Build code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


# ---------------- VERSION ----------------
  version:
    name: Extract version
    runs-on: ubuntu-latest
    needs: ci

    outputs:
      version: ${{ steps.v.outputs.version }}

    steps:
      - id: v
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF_NAME}
          else
            VERSION=dev-${GITHUB_RUN_NUMBER}
          fi
      
          echo "version=$VERSION" >> $GITHUB_OUTPUT

# ---------------- BUILD & PUSH ----------------
  docker:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: version

    env:
      VERSION: ${{ needs.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          

#------------ different method of writing build and push image============
#========== the first method this a better version/step to use.  the one with out #
  
      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ${{ env.IMAGE_NAME }}/frontend-dev:${{ env.VERSION }}
#         cache-from: type=gha
#         cache-to: type=gha,mode=max

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ${{ env.IMAGE_NAME }}/backend-dev:${{ env.VERSION }}
#         cache-from: type=gha
#         cache-to: type=gha,mode=max

#---------------OR----------------------------------

#      - name: Build & push frontend
#        run: |
#          docker build -t $IMAGE_NAME/frontend-dev:$VERSION backend
#          docker push $IMAGE_NAME/frontend-dev:$VERSION

#      - name: Build & push backend
#        run: |
#         docker build -t $IMAGE_NAME/backend-dev:$VERSION backend
#         docker push $IMAGE_NAME/backend-dev:$VERSION


# ---------------- VALIDATION ----------------
  validate:
    name: Validate Helm
    runs-on: ubuntu-latest
    needs: [docker, version]

    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4

      - name: Helm lint
        run: helm lint helm/todo-app

      - name: Helm template validate
        run: |
          helm template helm/todo-app \
            --set image.tag=${{ needs.version.outputs.version }} \

# ---------------- GITOPS ----------------
  gitops:
    name: Update ArgoCD Repo
    runs-on: ubuntu-latest
    needs: [validate, version]

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: your-org/gitops-repo
          token: ${{ secrets.GITOPS_TOKEN }}


      - name: Setup yq
        uses: mikefarah/yq@v4.54.4

      - name: Update Helm values
#        if: startsWith(github.ref, 'refs/tags/v')       # these means if the image tag doesn't have v it will not push/update helm chart
        run: |
          VERSION=${{ needs.version.outputs.version }}          
          yq -i '.image.tag = strenv(VERSION)' helm/todo-app/values.yaml

#          sed -i "s/tag:.*/tag: \"${VERSION}\"/" helm/todo-app/values.yaml        

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/todo-app/values.yaml
          git commit -m "update image tag to ${{ needs.version.outputs.version }}" || echo "no changes"
          git push
